# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQ0Wtt2ae7QSnLdsCOnOxNJnfEKkUkd8
"""

!pip install tensorflow streamlit pillow numpy

import os

# Define the base directory for the structured dataset
base_processed_dir = '/content/structured_cats_dogs'

# List the contents of the structured dataset directory
print(f"Listing contents of {base_processed_dir}:")

# Use os.walk to get a more detailed view of the directory structure
for dirpath, dirnames, filenames in os.walk(base_processed_dir):
    # Calculate current depth for indentation
    depth = dirpath.replace(base_processed_dir, '').count(os.sep)
    indent = '  ' * depth

    # Print current directory
    print(f"{indent}[{os.path.basename(dirpath)}]")

    # Print subdirectories
    for dname in dirnames:
        print(f"{indent}  |- {dname}/")
    # Print first 5 files if there are any, and total count
    if filenames:
        print(f"{indent}  |- ... ({len(filenames)} files)")
        for fname in sorted(filenames)[:5]: # Print a few sample files
            print(f"{indent}  |   |- {fname}")


print("\nVerification complete.")

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# Load model
model = tf.keras.models.load_model("/content/cats_dogs_model.h5")

st.title("🐱🐶 Cats vs Dogs Classifier")
st.write("Upload an image and the model will predict whether it is a cat or a dog.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).resize((150, 150))
    st.image(image, caption="Uploaded Image", use_column_width=True)

    img_array = np.array(image) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)[0][0]

    if prediction > 0.5:
        st.success("🐶 This is a Dog!")
    else:
        st.success("🐱 This is a Cat!")